const mongoose=require('mongoose');
//require('@mongoosejs/double');

const ProviderSchema=new mongoose.Schema(
    {
        username:{
            type:String,
            required:true,
            unique:true,
            lowercase:true,
            index:"text"
        },
        password:{
            type:String,
            required:true
        },
        name:{
            type:String,
            required:true,
            unique:true
        },
        address:{
            type:String,
            required:true
        },
        contact_no:[
            {
                type:String
            }
        ],
        email:{
            type:String,
            required:true,
            lowercase:true,
            unique:true
        },
        no_of_vote:{
            type:Number,
            default:0,
            required:true
        },
        rating:{
            type:Number,
            default:0,
            required:true
        },
        bank_acc_no:{
            type:String,
            required:true,
            unique:true
        },
        owner:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Owner',
            required:true
        },
        service:[
            {
                type:String,
                lowercase:true
            }
        ],
        membership:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Membership',
            required:true
        },
        workingRange:[
            {
                type:String
            }
        ]
        ,
        joined_at:{
            type:Date,
            required:true,
            default:Date.now
        },
        state:{
            type:String,
            required:true,
            lowercase:true,
            default:'registered',
            enum:['registered','approved','blocked']
        },
        profile:{
            type:String,
            required:true,
            default:"sp.jpg"
        }

    }
);
const ServiceProvider=mongoose.model('ServiceProvider',ProviderSchema);
module.exports = ServiceProvider;
